export const services = [
{key:"New SIM",icon:"📱",desc:"Get assistance with a new Airtel SIM connection, documentation and activation.",cta:"Get SIM",features:["New connection assistance","Documentation guidance","Activation support"]},
{key:"Prepaid",icon:"🔋",desc:"Explore Airtel prepaid recharge plans and choose a plan according to your connectivity requirements.",cta:"Explore Prepaid",features:["Flexible recharge options","Data plans and calling benefits","Available recharge offers","Easy recharge assistance"]},
{key:"Postpaid",icon:"🧾",desc:"Get Airtel postpaid connectivity with data, calling and entertainment benefits depending on the selected plan.",cta:"Get Postpaid",features:["Monthly billing","Data and calling benefits","Available 5G benefits","Family plan options","Entertainment benefits on eligible plans","SIM delivery options"]},
{key:"5G",icon:"⚡",desc:"Experience Airtel's next-generation mobile connectivity on compatible devices and in eligible coverage areas.",cta:"Know More",features:["Fast connectivity for everyday activities","Streaming and entertainment","Video calls and remote work"]},
{key:"Wi-Fi",icon:"📶",desc:"Get high-speed home internet for work, entertainment, streaming, gaming and everyday connectivity.",cta:"Get Wi-Fi",features:["Plans with speeds up to 1 Gbps (depends on availability and plan)","Multiple devices, work from home, gaming","OTT entertainment on eligible plans","Wi-Fi router and installation assistance"]},
{key:"DTH",icon:"📺",desc:"Enjoy television entertainment with Airtel DTH and available channel and entertainment options.",cta:"Get DTH",features:["TV channels and HD entertainment","Channel options","Recharge and service assistance"]},
{key:"Port to Airtel",icon:"🔁",desc:"Switch your existing mobile number to Airtel and get assistance with the porting process.",cta:"Port Now",features:["Request porting/UPC (send PORT to 1900)","Complete KYC/document verification","Receive your Airtel SIM","Complete activation"]},
{key:"eSIM",icon:"🧩",desc:"Get assistance with Airtel eSIM activation for compatible smartphones and devices.",cta:"Enquire Now",features:["No physical SIM on eSIM-compatible devices","Digital activation process","Compatible smartphone support"]},
{key:"Airtel Black",icon:"🖤",desc:"Explore eligible Airtel bundled services with convenient service management and billing options.",cta:"Explore Airtel Black",features:["Eligible Postpaid Mobile, Wi-Fi and DTH combinations","Single billing experience","Convenient service management","Subject to eligibility and plan conditions"]},
{key:"Airtel Business",icon:"🏢",desc:"Business connectivity solutions for offices, organizations and enterprises.",cta:"Business Enquiry",features:["Office Internet","Corporate Postpaid","Dedicated Internet","Enterprise Connectivity","Cloud & Digital Solutions"]},
{key:"International Roaming",icon:"🌍",desc:"Get assistance with Airtel international roaming services and available roaming options.",cta:"Explore Roaming",features:["Roaming plans","Calling, mobile data and SMS","Assistance while travelling"]},
{key:"Recharge & Plans",icon:"💳",desc:"Get assistance with available Airtel recharge plans, postpaid bills, DTH and Wi-Fi services.",cta:"View Plans",features:["Prepaid recharge","Postpaid bill assistance","DTH and Wi-Fi recharge"]}
]
